DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS SELLER;

CREATE TABLE PRODUCT(
	PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(250) NOT NULL,
	PRICE DECIMAL NOT NULL,
	COLOR VARCHAR(250) NOT NULL,
	SIZE INT NOT NULL,
	SKU VARCHAR(250) NOT NULL
);

CREATE TABLE SELLER(
	PRODUCT_ID INT NOT NULL,
	SELLER VARCHAR(250) NOT NULL,
	QUANTITY INT NOT NULL,
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

